import java.util.ArrayList;

public class Driver {
   static ArrayList<Integer> alignmentScores;
   static String sequence, pattern;
   static int gapPenalty;
   static int[][] subMat;
   
   public static void main(String[] args) {
      alignmentScores = new ArrayList<Integer>();
      
      //Testing purposes//
      //sequence = "HsTSCMAQQANVGELLAMLDSPMLGVRDDVTAVFKENLNSDRGPMLVNTLVDYYLETSSQPALHILTTLQEPHDKHLLDRINEYVGKAATRLSILSLLGHVIRLQPSWKHKLSQAPLLPSLLKCLKMDTDVVVLTTGVLVLITMLPMIPQSGKQHLLDFFDIFGRLSSWCLKKPGHVAEVYLVHLHASVYALFHRLYGMYPCNFVSFLRSHYSMKENLETFEEVVKPMMEHVRIHPELVTGSKDHELDPRRWKRLETHDVVIECAKISLDPTEASYEDGYSVSHQISARFPHRSADVTTSPYADTQNSYGCATSTPYSTSRLMLLNMPGQLPQTLSSPSTRLITEPPQATLWSPSMVCGMTTPPTSPGNVPPDLSHPYSKVFGTTAGGKGTPLGTPATSPPPAPLCHSDDYVHISLPQATVTPPRKEERMDSARPCLHRQHHLLNDRGSEEPPGSKGSVTLSDLPGFLGDLASEEDSIEKDKEEAAISRELSEITTAEAEPVVPRGGFDSPFYRDSLPGSQRKTHSAASSSQGASVNPEPLHSSLDKLGPDTPKQAFTPIDLPCGSADESPAGDRECQTSLETSIFTPSPCKIPPPTRVGFGSGQPPPYDHLFEVALPKTAHHFVIRKTEELLKKAKGNTEEDGVPSTSPMEVLDRLIQQGADAHSKELNKLPLPSKSVDWTHFGGSPPSDEIRTLRDQLLLLHNQLLYERFKRQQHALRNRRLLRKVIKAAALEEHNAAMKDQLKLQEKDIQMWKVSLQKEQARYNQLQEQRDTMVTKLHSQIRQLQHDREEFYNQSQELQTKLEDCRNMIAELRIELKKANNKVCHTELLLSQVSQKLSNSESVQQQMEFLNRQLLVLGEVNELYLEQLQNKHSDTTKEVEMMKAAYRKELEKNRSHVLQQTQRLDTSQKRILELESHLAKKDHLLLEQKKYLEDVKLQARGQLQAAESRYEAQKRITQVFELEILDLYGRLEKDGLLKKLEEEKAEAAEAAEERLDCCNDGCSDSMVGHNEEASGHNGETKTPRPSSARGSSGSRGGGGSSSSSSELSTPEKPPHQRAGPFSSRWETTMGEASASIPTTVGSLPSSKSFLGMKARELFRNKSESQCDEDGMTSSLSESLKTELGKDLGVEAKIPLNLDGPHPSPPTPDSVGQLHIMDYNETHHEHS";
      //pattern = "TMLPMIPQSGKQHLLDFFDIFGRL";
      sequence = "ATTGACT";
      pattern = "ATGTAT";
      gapPenalty = 3;
      subMat = BLOSUM.getMatrix();
      //End Testing Purposes//
      
      sequence = sequence.toUpperCase();
      pattern = pattern.toUpperCase();
      
      for(int i = 0; i < 1; i++) {
         Alignment alignment = new Alignment(sequence, pattern, gapPenalty, subMat);
         alignmentScores.add(alignment.getAlignmentScore());
      }
      
      printScores();
   }
   
   
   private static void printScores() {
      for(Integer score : alignmentScores) {
         System.out.println(score);
      }
   }
}